#ifndef SPECIFIC_TYPES_HPP_
#define SPECIFIC_TYPES_HPP_

#define SHORT_NAME_SIZE 30u
#define NUMBER_OF_ATTRIBUTES 6u
#define NUMBER_OF_DAMAGE_TYPES 6u
#define LONG_NAME_SIZE 50u


#endif // SPECIFIC_TYPES_HPP_